version: '3'
services:
  app:
    build: .
    ports:
      - "8008:8008"  # Map the container's port to the host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["node", "index.js"]  # Command to run your Express app