DELETE FROM MenuTb;
DELETE FROM SidesTb;
DELETE FROM DrinksTb;

SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE '/app/menuStore/menu.csv'
INTO TABLE MenuTb
CHARSET utf8
FIELDS
TERMINATED BY ','
ENCLOSED BY '"'
LINES
TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE '/app/menuStore/sides.csv'
INTO TABLE SidesTb
CHARSET utf8
FIELDS
TERMINATED BY ','
ENCLOSED BY '"'
LINES
TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE '/app/menuStore/drinks.csv'
INTO TABLE DrinksTb
CHARSET utf8
FIELDS
TERMINATED BY ','
ENCLOSED BY '"'
LINES
TERMINATED BY '\n'
IGNORE 1 LINES
;
