DELETE FROM MenuTb;
DELETE FROM SidesTb;
DELETE FROM DrinksTb;

SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE 'menu.csv'
INTO TABLE MenuTb
CHARSET utf8
FIELDS
TERMINATED BY ','
ENCLOSED BY '"'
LINES
TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE 'sides.csv'
INTO TABLE MenuTb
CHARSET utf8
FIELDS
TERMINATED BY ','
ENCLOSED BY '"'
LINES
TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE 'drinks.csv'
INTO TABLE MenuTb
CHARSET utf8
FIELDS
TERMINATED BY ','
ENCLOSED BY '"'
LINES
TERMINATED BY '\n'
IGNORE 1 LINES
;